### ISSUE TITLE
Figure out how to incorporate Fedora's (and openSUSE's) lib64 patches on Python 3.7/3.8

### ISSUE THREAD

**Issue by hroncok** [pypa/distutils#110]
See https://github.com/PyCQA/pylint/issues/5704 and https://github.com/pypa/setuptools/pull/2896#issuecomment-1018919156

Apparently, I have completely forgotten that on Python < 3.9, we do patch distutils in one more way: We replace /usr/lib with /usr/lib64 on 64bit architectures.

See our patches:

- Python 3.8: https://github.com/fedora-python/cpython/commit/31397a898360564316fed0c54051685122a9554a
- Python 3.7: https://github.com/fedora-python/cpython/commit/76a09bcaa175a3e501b4d69a71ed7f30b1cefe95

I am opening this issue to track this problem. I don't expect you to fix it, I plan to have a look, but not today.

**Comment by hroncok** [comment]
Looking at the current implementation of pypa/distutils, it seems we only need to set `sys.platlibdir` to `"lib64"` and it should work as expected :)

**Comment by hroncok** [comment]
Work in progress PR for python3.8: https://src.fedoraproject.org/rpms/python3.8/pull-request/54

**Comment by jaraco** [comment]
I'll confess, I'm slightly uneasy with altering a value in `sys`, but when I look at the schemes, `{platlibdir}` resolves directly from `sys.platlibdir`, so I agree with the conclusion. I wonder what effect changing that value will have on other environments, such as venv or virtualenv.

**Comment by hroncok** [comment]
Yeah, my idea is to set it, and try to see what it breaks.

**Comment by hroncok** [comment]
Nothing broke for me, @encukou or @jnsnow. Let's share this with the crowds. Fedora updates:

 - [python3.8-3.8.12-6.fc35](https://bodhi.fedoraproject.org/updates/FEDORA-2022-bee534f152)
 - [python3.8-3.8.12-6.fc34](https://bodhi.fedoraproject.org/updates/FEDORA-2022-2f3a7c7f06)
 - [python3.7-3.7.12-8.fc35](https://bodhi.fedoraproject.org/updates/FEDORA-2022-61699bd6f8)
 - [python3.7-3.7.12-8.fc34](https://bodhi.fedoraproject.org/updates/FEDORA-2022-8b7e9457a2)

The updates will soon be installable from the `updates-testing` repo.

**Comment by hroncok** [comment]
Yes, it is hopefully resolved for Fedora at least.
