### ISSUE TITLE
LTO fatal error: bytecode stream generated with LTO version 7.3 instead of the expected 6.2

### ISSUE THREAD

**Issue by xkszltl** [pypa/distutils#13]
## Environment

- Ubuntu 18.04
- gcc (7.5) and gcc-8 installed

## Issue

With 50.0.3, we hit an LTO issue when building cython.
<img width="949" alt="image" src="https://user-images.githubusercontent.com/5203025/92013795-d4cca680-ed80-11ea-82ee-2b0e8e8715d8.png">
```
    /usr/bin/gcc-8 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -flto -fuse-linker-plugin -ffat-lto-objects -fPIC -I/usr/include/python3.6m -c /tmp/pip-req-build-ybinyobt/Cython/Plex/Scanners.c -o build/temp.linux-x86_64-3.6/tmp/pip-req-build-ybinyobt/Cython/Plex/Scanners.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-3.6/tmp/pip-req-build-ybinyobt/Cython/Plex/Scanners.o -L/usr/lib -o build/lib.linux-x86_64-3.6/Cython/Plex/Scanners.cpython-36m-x86_64-linux-gnu.so
    lto1: fatal error: bytecode stream in file 'build/temp.linux-x86_64-3.6/tmp/pip-req-build-ybinyobt/Cython/Plex/Scanners.o' generated with LTO version 7.3 instead of the expected 6.2
    compilation terminated.
    lto-wrapper: fatal error: /usr/bin/x86_64-linux-gnu-gcc returned 1 exit status
    compilation terminated.
    /usr/bin/ld: error: lto-wrapper failed
    collect2: error: ld returned 1 exit status
    error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
```

With 49.6.0 it was fine.

**Comment by jaraco** [comment]
Can you provide some hints as to how to reproduce the error?

**Comment by xkszltl** [comment]
Yes it's link-time optimization.
With LTO, object files contains high level IR which can be further optimized by linker, but the format is specific to each compiler versions, so requires proper plugin or compiler frontend to be used.
This is usually an indication of multiple toolchain are mistakenly mixed together.

CentOS 7 by default uses gcc 4, but provided a list of extra compilers (i.e. devtoolset-9 for gcc-9).

Rebuild with 50.1.0 passed.

**Comment by xkszltl** [comment]
I don't have a minimum repro in hand, but most likely this is the workflow to trigger it:
1. `sudo yum install centos-release-scl -y && sudo yum install devtoolset-9 -y` on CentOS 7
2. `. scl_source enable devtoolset-9`, which setup the env var for gcc 9.
3. You can double check with `gcc --version`
4. Now install latest released setuptools and cython from git URL: `/usr/bin/sudo -E PATH="$PATH" python3 -m pip install -Uv git+xxxxxxxxxx`

This is the full script I used to do this in case you need.
Can be run as `pkgs/utils/pip_install_from_git.sh cython/cython`, assuming devtoolset-9 and python3 were installed.
https://github.com/xkszltl/Roaster/blob/56a4e010572d14f5e74c6c0fd5a7133f38e4e6fd/pkgs/utils/pip_install_from_git.sh#L98

**Comment by jaraco** [comment]
I've gotten as far as installing the settings you described above, but I've been unable to replicate the issue.

```
draft $ cat Dockerfile
FROM centos:7
RUN yum install centos-release-scl -y
RUN yum install devtoolset-9 -y
RUN yum install python3-devel -y
RUN yum install git -y
SHELL [ "/usr/bin/scl", "enable", "devtoolset-9"]
RUN python3 -m pip install -U pip setuptools==50.0.3
ENV SETUPTOOLS_USE_DISTUTILS=local
CMD gcc --version && pip install git+https://github.com/cython/cython
draft $ docker run -it @($(docker build -q .).strip())
gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Collecting git+https://github.com/cython/cython
  Cloning https://github.com/cython/cython to /tmp/pip-req-build-thoiqlbd
Using legacy 'setup.py install' for Cython, since package 'wheel' is not installed.
Installing collected packages: Cython
    Running setup.py install for Cython ... done
Successfully installed Cython
```

There must be some other factor at play.

**Comment by xkszltl** [comment]
> `CMD gcc --version && pip install git+https://github.com/cython/cython`

FYI on CentOS 7 pip is from python2

My fault, this is Ubuntu-specific issue, not CentOS.
Here's the repro:
```
FROM ubuntu:18.04
SHELL ["/bin/bash", "-c"]
RUN apt-get update -y
RUN DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y gcc{,-{7,8}} python3{,-pip} git
RUN gcc --version && gcc-7 --version && gcc-8 --version
RUN python3 --version
RUN python3 -m pip --version
RUN python3 -m pip install -Uv pip setuptools==50.0.3
RUN python3 -m pip --version
RUN set -e; \
    export CC=gcc-8 CXX=g++-8; \
    SETUPTOOLS_USE_DISTUTILS=stdlib python3 -m pip install -Uv git+https://github.com/cython/cython@0.29.21;
RUN set -e; \
    export CC=gcc-8 CXX=g++-8; \
    SETUPTOOLS_USE_DISTUTILS=local python3 -m pip install -Uv git+https://github.com/cython/cython@0.29.21;
```

**Comment by jaraco** [comment]
That really helps. Thanks!

I've pared down the repro a tiny bit:

```
FROM ubuntu:18.04
RUN apt update -y
ENV DEBIAN_FRONTEND=noninteractive
RUN apt upgrade -y
RUN apt install -y gcc gcc-8 python3-pip
RUN gcc --version && gcc-8 --version
RUN python3 -m pip install -U pip setuptools
ENV CC=gcc-8 CXX=g++-8
ENV SETUPTOOLS_USE_DISTUTILS=local
RUN python3 -m pip install --no-binary cython cython==0.29.21
```

I found that `s/18.04/20.04/` and the problem goes away, suggesting a change in the OS or in the default Python 3 is pertinent.

**Comment by jaraco** [comment]
Building on Python 3.7 on Ubuntu Bionic (18.04) seems to work fine:

```
FROM ubuntu:18.04
RUN apt update
ENV DEBIAN_FRONTEND=noninteractive
RUN apt upgrade -y
RUN apt install -y software-properties-common
RUN apt-add-repository -y ppa:deadsnakes
RUN apt update
RUN apt install -y gcc gcc-8 python3-pip python3.7-dev wget
RUN sh -c "wget https://bootstrap.pypa.io/get-pip.py -O - | python3.7"
RUN gcc --version && gcc-8 --version
RUN python3.7 -m pip install -U pip setuptools
ENV CC=gcc-8 CXX=g++-8
ENV SETUPTOOLS_USE_DISTUTILS=local
RUN python3.7 -m pip install --no-binary cython cython==0.29.21
```

Interestingly, building on Ubuntu Focal with Python 3.6 also seems to work just fine:

```
FROM ubuntu:focal
RUN apt update
ENV DEBIAN_FRONTEND=noninteractive
RUN apt upgrade -y
RUN apt install -y software-properties-common
RUN apt-add-repository -y ppa:deadsnakes
RUN apt update
RUN apt install -y gcc gcc-8 python3-pip python3.6-dev wget
RUN sh -c "wget https://bootstrap.pypa.io/get-pip.py -O - | python3.6"
RUN gcc --version && gcc-8 --version
RUN python3.6 -m pip install -U pip setuptools
ENV CC=gcc-8 CXX=g++-8
ENV SETUPTOOLS_USE_DISTUTILS=local
RUN python3.6 -m pip install --no-binary cython cython==0.29.21
```

**Comment by jaraco** [comment]
So the issue appears to be peculiar to Ubuntu 18.04 and Python 3.6. I'm way out of my depth on this one - I could use some help narrowing down the issue. The issue is likely due to some debian-specific patches applied to distutils. In 06d2c56b, I applied debian patches to the distutils code, that commit might have a hint as to what might be different (although it's for Python 3.8.4 and not 3.6 as found on Bionic). Perhaps Debian has some peculiar patches for that version of distutils.

What is it that's causing a mismatch of LTO versions? What file is mismatching with what other file? What factors affect the version of LTO? How could the changes to distutils be affecting the LTO version of these files?

**Comment by xkszltl** [comment]
LTO version depends on the compiler version.
A mix of compilers can causes this.
When linking, either the linker found several inputs (`.o` or `.a`) contains different LTO format, or the linker is from a different version which doesn't work with its inputs.

Note Ubuntu 18.04 has gcc 7 as default compiler, which was also used to compile the pkgs in this distro.
Ubuntu 20.04 uses gcc 9.

**Comment by jaraco** [comment]
So presumably Debian has built something (libpython?) with LTO 6.2, but because the later distutils is adopted from Python 3.9, it includes changes that opt in to LTO 7.3. Since this new distutils is meant to support Python 3.5+, it probably now needs to be more aware of the Python version and fall back to older LTO settings when on older Pythons.

Or an alternate explanation may be that Cython is doing something clever with distutils, and the mismatch lies in Cython's logic.

Would you be willing to dig deeper and narrow the problem further? In particular:

- Determine if the issue happens with packages other than Cython.
- Determine if it's possible to replicate the issue with a simple Python package.
- Trace the source of LTO settings to determine which libraries get which versions and why.

**Comment by xkszltl** [comment]
- Personally I haven't seen it with other packages, but because most of packages we used has cython as dependency, it is in an relative early stage of our build, and could potentially affect our statistics.
- I'm not an expert of either cython (in fact I almost never use it directly) or distutil, so not sure if there's anything I can do.
- Usually LTO version depends on the compiler used.

I wonder if you can open an issue to cython?
As domain experts, I believe you guys can quickly figure out what's going on.

**Comment by jaraco** [comment]
I'm afraid I won't have the bandwidth or expertise to help here. I'll be happy to help review a patch or help test in an environment, but when it comes to driving the issue, I'm unfortunately going to have to rely on others in the community to drive. I would recommend you to reach out to a support forum (maybe in Cython community) for assistance. The issue may not be Cython specific either -- this issue may affect C extensions generally, so I'd be cautious to exclude that possibility first.

**Comment by xkszltl** [comment]
I'm fine with the revert of `SETUPTOOLS_USE_DISTUTILS` in 50.1.0.
Given you already had an repro, maybe add that to CI test so that it can be fixed before when re-enabling new behavior as default?

**Comment by xkszltl** [comment]
I've help filed the issue to cython side and they seem to have the same guess: wrong linker was called in Ubuntu's mixed multi-toolchain setup, and this could be an issue for any c extension with LTO.

**Comment by jaraco** [comment]
In that case, it should be possible to create a reproducer within pure distutils or setuptools, and that should make it easier to trace the underlying condition(s) that lead to the unexpected behavior.

**Comment by jaraco** [comment]
Given that Python 3.6 is reaching end of life and there isn't anybody with enough experience and interest to work around the issue, I'm going to declare defeat and say this problem can't be fixed. Users on affected Ubuntu/Debian versions will need to work around the issue by disabling the distutils adoption (`SETUPTOOLS_USE_DISTUTILS=stdlib`) or pin to older versions of Setuptools once `local` becomes the default.

I welcome others to investigate deeper and devise a solution. Maybe one should diff distutils between Python 3.6 and 3.7 or inspect differences in Debian distutils patches between those Python versions to see if they provide any clue as to what behavior needs to change.

**Comment by isuruf** [comment]
https://github.com/pypa/distutils/pull/53 should fix this.

**Comment by isuruf** [comment]
The issue was that `CC=gcc-8` was used by distutils to compile, but `x86_64-linux-gnu-gcc` was used by distutils to link because LDSHARED was not overriden. #53 takes care of it by overriding LDSHARED when CC is set.

**Comment by isuruf** [comment]
As to why this was seen in 3.6 and not 3.7, that's because `-flto` was only in 3.6

**Comment by xkszltl** [comment]
Thanks @isuruf ! 
This is also my first time to know about the existence of $LDSHARED.
Is it Python-specific?

**Comment by isuruf** [comment]
Yes, it's a distutils specific env variable.
