### ISSUE TITLE
Wrong EXT_SUFFIX on python 3.7 on Windows

### ISSUE THREAD

**Issue by axnsan12** [pypa/distutils#130]
Delegating `get_config_var` to the built-in sysconfig breaks extension module builds with python 3.7 (and unpatched 3.8, 3.9 installs) on windows.

For context see pypa/setuptools#3219

Pasting the contents below:

-----------

### setuptools version

`>=61`

### Python version

3.7

### OS

Windows

### Description

This setuptools commit changed the bundled `distutils.sysconfig` to transparently forward `get_config_var` to the interpreter builtin sysconfig: https://github.com/pypa/setuptools/commit/4b313f0d8600e8957736df7d0ffb795d187ab955

However, as mentioned in [this python bug](https://bugs.python.org/issue39825), sysconfig is (was) broken and returns a bad EXT_SUFFIX on python >=3.7. The issue was [fixed in 3.10](https://github.com/python/cpython/commit/c0afb7fa0ebd1c0e95c0760bbe75a99a8dd12ea6), with a backport into 3.8 and 3.9, however 3.7 was completely left behind.

This problem was [mentioned on the setuptools issue tracker](https://github.com/pypa/setuptools/issues/2261#issuecomment-687060141) in the past, but the knowledge seems to since have slipped the collective mind.

Since setuptools hijacks `import distutils` by default, this means that anyone using python 3.7, or an older 3.8 or 3.9 installation, will suddenly start getting a wrong `EXT_SUFFIX` by simply updating to `setuptools>=61`, and the only way to get back the correct behavior is to `set SETUPTOOLS_USE_DISTUTILS=stdlib` to prevent the hijacking. Given this overarching impact I believe it's unfair to impose such a breaking change on users unsuspectingly using older python versions.

Notably, this completely breaks CMake builds of extension modules with FindPython when using affected python versions, since [they use `distutils.sysconfig`](https://gitlab.kitware.com/cmake/cmake/-/blob/843d1d198d15f65781d71118573461fb03a3101c/Modules/FindPython/Support.cmake#L503) to determine the required EXT_SUFFIX.

### Expected behavior

Return proper EXT_SUFFIX on any python version >=3.7 (e.g. `.cp37-win_amd64.pyd`)

### How to Reproduce

1. Install `setuptools>=61`
2. `py -3.7 -c "from distutils import sysconfig; print(sysconfig.get_config_var('EXT_SUFFIX'))"`

### Output

```console
.pyd
```

**Comment by isuruf** [comment]
Fixed in https://github.com/pypa/distutils/pull/131
