### ISSUE TITLE
Add support for MSVC 14.X to cygwinccompiler

### ISSUE THREAD

**Issue by andrasm62** [pypa/distutils#14]
We are using mingw32 on Windows and we got this error message:
```python
File "C:\Users\ANDRAS~1.MEN\AppData\Local\Temp\pip-build-env-vbdit7j6\overlay\Lib\site-packages\setuptools\_distutils\cygwinccompiler.py", line 84, in get_msvcr
raise ValueError("Unknown MS Compiler version %s " % msc_ver)
ValueError: Unknown MS Compiler version 1916
```

Adding the MSVC 14.X compilers to the conditions would solve the problem.

We also use Anaconda. It seems like they know about this and they have inserted a hack into their distutils package. If we force to use Anaconda's distutils instead of setuptools/_distutils, we don't get this error and we can compile C codes.

Could you update this file? I saw that setuptools seems to support MSVC 14.X versions, and probably this file wasn't updated because the code coverage is 0%, because it is used just in a very special situation.

**Comment by andrasm62** [comment]
Thank you!

I think adding the missing MSVC versions from the supported [WindowsCompilers](https://wiki.python.org/moin/WindowsCompilers) from the Python Wiki to the elif conditions will solve the probleme.

**Comment by jaraco** [comment]
Thanks for providing that reference. That document indicates that Setuptools is required.

Do you know where Anaconda maintains those patches? Are they open source? Can they be incorporated here? Would you be willing to drive this effort and develop/solicit a patch to add MSVC 14 support to distutils?

**Comment by andrasm62** [comment]
After a little research I found where the patches are: https://github.com/conda-forge/python-feedstock/tree/master/recipe/patches

The actual patch for distutils is a bit dirty I think, it uses a >= operator for the msc_ver variable.
Yes, I can do a patch.

**Comment by jaraco** [comment]
Sorry for the delayed response.

> do I need to write or run a test also?

Ideally, yes. See the test_cygwincompiler for the existing tests. This project does enable running the tests with [tox](https://pypi.org/project/tox).

It sounds like you may be a little new to this project, so at the risk of dissuading, your best next step may be to find a mentor or partner, someone more familiar with Python development and particularly with Anaconda and Cygwin development, to assist with the effort, as I'll likely not have the bandwidth or knowledge to help effectively.

**Comment by isuruf** [comment]
Fixed in https://github.com/pypa/distutils/pull/41
