### ISSUE TITLE
install numpy error

### ISSUE THREAD

**Issue by houshijie-2020** [pypa/distutils#176]
1 i clone nogil into d:/nogil 
2 i compile nogil with build.bat -p x64 -m 
3 i copy all the files of D:\nogil\amd64  to d:/nogil  
4 i add d:/nogil  and d:/nogil/Scripts to path
5 i run this shell to install cpyton module：python install cpyton;
6 i run this shell to install pip：pthon get-pip.py
6 when i run pip install numpy.it report an error as below:
      CPU dispatch  :
        Requested   : 'max -xop -fma4'
        Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
        Generated   : none
      INFO: CCompilerOpt.cache_flush[857] : write cache to path -> D:\Users\80280060\AppData\Local\Temp\pip-install-oqk_b6kk\numpy_b4d28da6cfb84c9aba824e9fe2bbd3e2\build\temp.win-amd64-3.9\ccompiler_opt_cache_clib.py
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  **ERROR: Failed building wheel for numpy**
Failed to build numpy
**ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects**

**Comment by jaraco** [comment]
Hi houshijie. I don't think there's much I can do with this report. If you have problems with `pip install numpy`, please follow the support channels for numpy unless they direct you here that you have a bug with distutils.
