### ISSUE TITLE
Are the docs/ live / hosted anywhere?

### ISSUE THREAD

**Issue by tony** [pypa/distutils#19]
I'd like to link via intersphinx to `LooseVersion` in an API reference, are these docs live anywhere?

If not, is there an intent to host them somewhere?

Thank you!

**Comment by jaraco** [comment]
Currently, there are no plans to host the documentation. It's conceivable that the docs will be merged into Setuptools and never hosted separately. If/when that happens, I'd expect for LooseVersion not to be part of the supported/documented interface.

**Comment by jaraco** [comment]
Oh. I'd forgotten. Setuptools _does_ already host the [distutils docs](https://setuptools.readthedocs.io/en/latest/deprecated/distutils/index.html). You're welcome to link there if needed, but given the deprecation of that space, I'd recommend against it.
