### ISSUE TITLE
build with --py-limited-api does not link library with -lpython3 on Windows with mingw32-x64

### ISSUE THREAD

**Issue by genotrance** [pypa/distutils#229]
https://github.com/pypa/setuptools/issues/4224 describes the entire issue and I was told to reopen here. Ideally we could move that issue here. Originally started with https://github.com/python-cffi/cffi/issues/61 who redirected to setuptools.

To summarize - mingw32 works great on Windows with `--py-limited-api=cp32` and `--compiler=mingw32`, except for linking to the specific Python version `-lpython312`. If I manually change the link command to `-lpython3` and update the wheel, it works on all Python versions. So the compile works fine, just not the link.

**Comment by lazka** [comment]
I've added a comment to the source issue: https://github.com/pypa/setuptools/issues/4224#issuecomment-1975792231

**Comment by lazka** [comment]
I think this should be moved to setuptools, because py-limited-api is not part of distutils.

**Comment by genotrance** [comment]
Closing this issue - the setuptools patch fixes the issue for me. Hoping it gets picked up by upstream.
