### ISSUE TITLE
`[default: ]` vs. `(default: )`

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [pypa/distutils#251]
I see a mixture of `[default: ...]` and `(default: ...)` for default values of user options.

* 24 occurrences of `[default: ...]`, for example:
  
  https://github.com/pypa/distutils/blob/e5b06e144d1e57e0efebbc943bf071cd22e46da8/distutils/command/install_lib.py#L41-L46
* 11 occurrences of `(default: ...)`, for example:
  
  https://github.com/pypa/distutils/blob/e5b06e144d1e57e0efebbc943bf071cd22e46da8/distutils/command/install_data.py#L18-L23

Is it on purpose? If so, what meaning does either version convey? If not, would it be OK to standardise?

**Comment by DimitriPapadopoulos** [comment]
See https://github.com/pypa/setuptools/issues/4421.

**Comment by jaraco** [comment]
I'm unaware of any intent behind the difference. Feel free to spelunk the blame history to see if the commit messages provide any insight, or don't and we can proceed with standardizing. I have no preference.

**Comment by DimitriPapadopoulos** [comment]
The blame history of a few examples does not provide any insight.

I suggest using `[default: ]`. The closest to a "standard" that defines how default values should be printed is perhaps [docopt](http://docopt.org/):
> [...] and whether that argument has a default value (**`[default: 10]`**).
