### ISSUE TITLE
Outdated docstring for `_msvccompiler`

### ISSUE THREAD

**Issue by abravalheri** [pypa/distutils#290]
It seems that the modules `distutils.msvc9compiler` and `distutils.msvccompiler` no longer exist.

https://github.com/pypa/distutils/blob/58fe058e4d136625ee2d855e4bba63b3edd66dc3/distutils/_msvccompiler.py#L6-L7

**Comment by lazka** [comment]
There is also https://github.com/pypa/distutils/blob/main/conftest.py#L13-L16 which is slightly related
