### ISSUE TITLE
Unexpected TRY400 indicated in unchanged code

### ISSUE THREAD

**Issue by jaraco** [pypa/distutils#292]
In the [feature/compilers-module-redux branch](https://github.com/pypa/distutils/tree/feature/compilers-module-redux), I'm attempting to refactor the code. When I do, a [TRY400](https://docs.astral.sh/ruff/rules/error-instead-of-exception/) error is indicated even though the code hasn't changed:

```
__________________________________________________________________ test session ___________________________________________________________________
distutils/compilers/C/msvc.py:163:9: TRY400 Use `logging.exception` instead of `logging.error`
    |
161 |         ).decode('utf-16le', errors='replace')
162 |     except subprocess.CalledProcessError as exc:
163 |         log.error(exc.output)
    |         ^^^^^^^^^^^^^^^^^^^^^ TRY400
164 |         raise DistutilsPlatformError(f"Error executing {exc.cmd}")
    |
    = help: Replace with `exception`
```

First off, that's a nuisance error. What if what I really wanted was to log just the error message? Ruff shouldn't be griping about legitimate usage of supported interfaces. If `logging.error` shouldn't ever be used, they should file that as a feature change to CPython to get that functionality deprecated.

Second, why is this error only emitted in the branch (bac29f15b), when the same code succeeds just fine in main?

@DimitriPapadopoulos What do you make of this error?

**Comment by 777Naity** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by DimitriPapadopoulos** [comment]
My understanding of the purpose of [`TRY400`](https://docs.astral.sh/ruff/rules/error-instead-of-exception/) is to suggest:
```python
try:
    i = 1 / 0
except ZeroDivisionError as exc:
    logging.exception('"my error message"')
```
instead of:
```python
try:
    i = 1 / 0
except ZeroDivisionError as exc:
    logging.error(f'"my error message" {exc}')
```
The output is considered more informative:
```
ERROR:root:"my error message"
Traceback (most recent call last):
  File "/volatile/home/dp165978/toto.py", line 4, in <module>
    i = 1 / 0
ZeroDivisionError: division by zero
```
instead of:
```
ERROR:root:"my error message" division by zero
```
In any case `logging.exception` was designed to log exceptions. However, I must admit it doesn't fit all use cases, especially when you just **want** to log `exc.output` and not details of `exc`! I guess `TRY400` needs to be disabled.

**Comment by DimitriPapadopoulos** [comment]
As for the second question, might ruff have been updated from 0.5 to 0.6?

**Comment by DimitriPapadopoulos** [comment]
I tried different versions of ruff (0.5.7, 0.6.1, 0.6.3) and cannot reproduce the error locally after removing the `noqa`:
```console
$ ruff check distutils/_msvccompiler.py
All checks passed!
$ ruff check --select TRY400 distutils/_msvccompiler.py
All checks passed!
$ 
```
I cannot reproduce it either in my [`TRY400`](https://github.com/DimitriPapadopoulos/distutils/tree/TRY400) in branch in #293.

This doesn't mean that we should keep `TRY400` though. It doesn't seem useful.

**Comment by DimitriPapadopoulos** [comment]
I can reproduce the issue with branch [feature/compilers-module-redux](https://github.com/pypa/distutils/tree/feature/compilers-module-redux) after removing `# noqa: RUF100, TRY400`. That's really peculiar!

Files [distutils/_msvccompiler.py](https://github.com/pypa/distutils/blob/971074d4a2f6e222cdbc43ce881586412c7ab8a1/distutils/_msvccompiler.py) from `main` branch and [distutils/compilers/C/msvc.py](https://github.com/pypa/distutils/blob/01807e171404387bbfba46ba856c58c2b768de8c/distutils/compilers/C/msvc.py) from `feature/compilers-module-redux` are almost identical. Yet, after removing `# noqa: RUF100, TRY400`, one the latter generates a `TRY400` while the former does not. I'll keep looking.

**Comment by DimitriPapadopoulos** [comment]
The reason is hidden in this change at the top of the file, in imports:
```diff
from ._log import log
from ..._log import log
```
In the former case, `log` does not seem to be properly identified as `logging.getLogger()`, thus `TRY400` is not emitted. That looks like a ruff bug, doesn't it?

**Comment by DimitriPapadopoulos** [comment]
However, I cannot reproduce the bug with a minimal example:
```
└── distutils
    ├── compilers
    │   └── C
    │       └── msvc.py
    ├── _log.py
    └── _msvccompiler.py
```
I get a `TRY400` in both cases:
```console
$ ruff check --select=TRY400
distutils/_msvccompiler.py:6:5: TRY400 Use `logging.exception` instead of `logging.error`
  |
4 |     i = 1 / 0
5 | except DivisionByZero as e:
6 |     log.error(f"raised {e}")
  |     ^^^^^^^^^^^^^^^^^^^^^^^^ TRY400
  |
  = help: Replace with `exception`

distutils/compilers/C/msvc.py:6:5: TRY400 Use `logging.exception` instead of `logging.error`
  |
4 |     i = 1 / 0
5 | except DivisionByZero as e:
6 |     log.error(f"raised {e}")
  |     ^^^^^^^^^^^^^^^^^^^^^^^^ TRY400
  |
  = help: Replace with `exception`

Found 2 errors.
No fixes available (2 hidden fixes can be enabled with the `--unsafe-fixes` option).
$ 
```
I have a hard time identifying which setting results in the silenced `TRY400` in the `main` branch.

**Comment by DimitriPapadopoulos** [comment]
The bug is triggered by the `distutils/__init__.py` file:
```
.
└── distutils
    ├── __init__.py
    ├── _log.py
    └── _msvccompiler.py
```
Even an **empty** `__init__.py` file silences `TRY400`:
```console
$ ruff check --select=TRY400
All checks passed!
$ 
```
After removing the empty `__init__.py` file:
```
.
└── distutils
    ├── _log.py
    └── _msvccompiler.py
```
I do see the `TRY400` error:
```console
$ ruff check --select=TRY400
distutils/_msvccompiler.py:6:5: TRY400 Use `logging.exception` instead of `logging.error`
  |
4 |     i = 1 / 0
5 | except DivisionByZero as e:
6 |     log.error(f"raised {e}")
  |     ^^^^^^^^^^^^^^^^^^^^^^^^ TRY400
  |
  = help: Replace with `exception`

Found 1 error.
No fixes available (1 hidden fix can be enabled with the `--unsafe-fixes` option).
$ 
```

**Comment by DimitriPapadopoulos** [comment]
I created https://github.com/astral-sh/ruff/issues/13225.

**Comment by jaraco** [comment]
Thanks for the investigation!
