### ISSUE TITLE
CXXFLAGS overrides default flags, CFLAGS doesn't

### ISSUE THREAD

**Issue by mglisse** [pypa/distutils#299]
https://github.com/pypa/distutils/blob/378984e02edae91d5f49425da8436f8dd9152b8a/distutils/sysconfig.py#L343-L345

distutils now uses CXXFLAGS instead of CFLAGS for C++, that's good. However, it was implemented differently: while CFLAGS is **appended** to the default flags, CXXFLAGS **replaces** them. Is there a particular reason for this inconsistency? I have an application where I was setting both CFLAGS and CXXFLAGS to the same value, and was quite confused when the behavior changed with the new setuptools.

**Comment by thesamesam** [comment]
Thanks @cjwatson. Let me take a look.

**Comment by cjwatson** [comment]
On second thoughts, based on pypa/setuptools#4836, I think this is just a bug in `persistent` that's been exposed by this change.  I've proposed https://github.com/zopefoundation/persistent/pull/214 to fix it.

**Comment by thesamesam** [comment]
Many thanks! That looks right to me and that the assertions were broken (and clearly haven't worked for at least some time).
