### ISSUE TITLE
Supporting MSYS2-MINGW python

### ISSUE THREAD

**Issue by naveen521kk** [pypa/distutils#34]
[MSYS2](https://www.msys2.org/) provides Python which is compiled with GCC on Windows and is widely used in projects like [`pygobject`](https://pygobject.readthedocs.io) and anything related to Gtk, where compiling them for normal python is difficult. Their python works, I have used it many times, but I have seen a *lot* of patches to make things work. See a list [here](https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-python). 

Currently, the following fails miserably because distutils always look for MSVC which isn't required in this version. Here, extensions should be compiled with GCC but support for that is missing in GCC, I think setuptools has them though, but doing something like this will fail.

```sh
$ export SETUPTOOLS_USE_DISTUTILS=local
$ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    from setuptools import Extension, setup
  File "C:/msys64/mingw64/lib/python3.8/site-packages/setuptools/__init__.py", line 241, in <module>
    monkey.patch_all()
  File "C:/msys64/mingw64/lib/python3.8/site-packages/setuptools/monkey.py", line 99, in patch_all
    patch_for_msvc_specialized_compiler()
  File "C:/msys64/mingw64/lib/python3.8/site-packages/setuptools/monkey.py", line 162, in patch_for_msvc_specialized_compiler
    patch_func(*msvc9('find_vcvarsall'))
  File "C:/msys64/mingw64/lib/python3.8/site-packages/setuptools/monkey.py", line 149, in patch_params
    mod = import_module(mod_name)
  File "C:/msys64/mingw64/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/setuptools/_distutils/msvc9compiler.py", line 295, in <module>
    raise DistutilsPlatformError("VC %0.1f is not supported by this module" % VERSION)
distutils.errors.DistutilsPlatformError: VC 6.0 is not supported by this module
```

The authors can surely help on how to get those in.

Thanks.

**Comment by lazka** [comment]
Just wanted to add that we are willing to help maintaining any cygwin/msys/mingw related parts in distutils if wanted. Just ping me if needed.

**Comment by lazka** [comment]
A more general question:

Various of the platform differences would be fixed if distutils.sysconfig and similar would defer to stdlib sysconfig (which we patch and control). But I see that stdlib sysconfig is only used in tests.

Is there any rule against using sysconfig directly? Or could be it be done, either for mingw as a special case, or in general?

**Comment by lazka** [comment]
> Various of the platform specific differences would be fixed if distutils.sysconfig and similar would defer to stdlib sysconfig (which we patch and control). But I see that stdlib sysconfig is only used in tests.

I've started this with some small changes: #91 and #92

**Comment by naveen521kk** [comment]
@jaraco Is there any deadline before which this needs to be done? That is, is there a date when support for using stdlib distutils is removed in setuptools?

I've got a bit busy recently and kind of forgot about this. I'll get to this when I get some time.
