### ISSUE TITLE
pypy3.8 install schema has python3.8 in it

### ISSUE THREAD

**Issue by isuruf** [pypa/distutils#56]
With recent main, `unix_prefix` is used which has python3.8 in it. See https://github.com/pypa/distutils/blob/main/distutils/command/install.py#L31-L37

cc @mattip

**Comment by jaraco** [comment]
Can you provide a bit more background? What is the expected behavior? When did the unexpected behavior emerge (why wasn't it a problem before)?

**Comment by isuruf** [comment]
PyPy3.8 which is still in RC stage will change its install layout and https://github.com/pypa/distutils/pull/51 was meant to address this change, but it was incomplete. PyPy3.7 and earlier site-packages was `<prefix>/site-packages` and PyPy3.8 site-packages is `<prefix>/lib/pypy3.8/site-packages`, but #51 changed it to `<prefix>/lib/python3.8/site-packages`.
