### ISSUE TITLE
Support Cygwin patches

### ISSUE THREAD

**Issue by jaraco** [pypa/distutils#73]
Also need to incorporate mingw/cygwin distutil patches - see https://github.com/pypa/distutils/pull/60#issuecomment-973277696, https://github.com/pypa/distutils/pull/60#issuecomment-980846735;
pypa/setuptools#2909 adds a CI for Cygwin

_Originally posted by @mkoeppe in https://github.com/pypa/setuptools/issues/2896#issuecomment-986278425_

**Comment by jaraco** [comment]
@mkoeppe Do you have a contact for Cygwin? Do you know what the Cygwin patches are?

Setuptools released two versions, 48 and  50, which twice attempted to adopt distutils into Setuptools, but there were emergent issues. I attempted to capture those emergent issues, but did not see anything reported from cygwin.

I'd really like to get this feature rolled out, as the longer it takes to get distutils adoption as the default, the more risk there is that changes to distutils will break use-cases that aren't being exercised.

Cygwin users will have the option to opt out by using `SETUPTOOLS_USE_DISTUTILS=stdlib`, but I would prefer if users did not have to do that, but I'm also reluctant to delay the rollout further.

Please do let us know more about what patches are present and how distutils might be able to incorporate that behavior.

**Comment by mkoeppe** [comment]
I don't have a cygwin contact, but the patches can be found at https://cygwin.com/git-cygwin-packages/?p=git/cygwin-packages/python38.git;a=tree

**Comment by mkoeppe** [comment]
In particular https://cygwin.com/git-cygwin-packages/?p=git/cygwin-packages/python38.git;a=blob;f=3.1-enable-new-dtags.patch;h=716af3b14d3483e5a4cdb65d0ec45ba92bd03ceb;hb=HEAD corresponds to the issue that I ran into that I mentioned in https://github.com/pypa/distutils/pull/60#issuecomment-980846735

**Comment by jaraco** [comment]
I've [reached out](https://cygwin.com/pipermail/cygwin/2021-December/250185.html) on the mailing list to raise awareness of the issue.

**Comment by mkoeppe** [comment]
Same for MSYS2 (mingw). Patches are here: https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-python

**Comment by mkoeppe** [comment]
For testing on MSYS2, there is a GH Action: https://github.com/msys2/setup-msys2

**Comment by jaraco** [comment]
Let’s track that project separately, even if some of the solutions may be similar.

**Comment by jaraco** [comment]
In email, Marco Atzeri responded:

Hi Jason,

currently we are not using any patch on SetupTools
Last I packaged is 59.5.0 for python 3.6 to 3.9

https://cygwin.com/packages/summary/python-setuptools-src.html

there are several patches on Python source that include the distutil portion

I just updated the patches used on last binaries on :

http://cygwin.com/git/cygwin-packages/python39.git
http://cygwin.com/git/cygwin-packages/python39.git

they are almost identical

General information on our python packages are also on:

https://cygwin.com/packages/summary/python38-src.html
https://cygwin.com/packages/summary/python39-src.html


--- 

It also included an attachment `3.8-distutils-cygwin.patch`:

```diff
--- origsrc/Python-3.8.0a4/Lib/distutils/cygwinccompiler.py	2019-05-06 14:30:25.000000000 -0400
+++ src/Python-3.8.0a4/Lib/distutils/cygwinccompiler.py	2019-05-19 14:35:55.872267300 -0400
@@ -92,9 +92,7 @@ class CygwinCCompiler(UnixCCompiler):
     compiler_type = 'cygwin'
     obj_extension = ".o"
     static_lib_extension = ".a"
-    shared_lib_extension = ".dll"
-    static_lib_format = "lib%s%s"
-    shared_lib_format = "%s%s"
+    shared_lib_extension = ".dll.a"
     exe_extension = ".exe"
 
     def __init__(self, verbose=0, dry_run=0, force=0):
--- origsrc/Python-3.8.0a4/Lib/distutils/unixccompiler.py	2019-05-19 14:24:27.779442200 -0400
+++ src/Python-3.8.0a4/Lib/distutils/unixccompiler.py	2019-05-19 14:35:55.872267300 -0400
@@ -81,6 +81,7 @@ class UnixCCompiler(CCompiler):
     xcode_stub_lib_format = dylib_lib_format
     if sys.platform == "cygwin":
         exe_extension = ".exe"
+        dylib_lib_extension = ".dll.a"
 
     def preprocess(self, source, output_file=None, macros=None,
                    include_dirs=None, extra_preargs=None, extra_postargs=None):
--- origsrc/Python-3.8.0b2/Misc/python.pc.in	2019-07-04 06:50:19.000000000 -0400
+++ src/Python-3.8.0b2/Misc/python.pc.in	2019-07-21 15:33:35.374399700 -0400
@@ -9,5 +9,5 @@ Description: Build a C extension for Pyt
 Requires:
 Version: @VERSION@
 Libs.private: @LIBS@
-Libs:
+Libs: @LIBPYTHON@
 Cflags: -I${includedir}/python@VERSION@@ABIFLAGS@
```

**Comment by lazka** [comment]
I've added a CI job in #82

**Comment by lazka** [comment]
1) From what I see #139 added the changes patched in https://cygwin.com/git-cygwin-packages/?p=git/cygwin-packages/python39.git;a=blob;f=3.8-distutils-cygwin.patch;h=70ce74d7daaffa9096d4b5e4faec32f26e358b9f;hb=HEAD

2) The only remaining patch is https://cygwin.com/git-cygwin-packages/?p=git/cygwin-packages/python38.git;a=blob;f=00001-rpath.patch;h=aad36128683812464d49ae7f8ff3124e6a71e99e;hb=HEAD which comes from Fedora https://src.fedoraproject.org/rpms/python3.10/blob/rawhide/f/00001-rpath.patch so it isn't cygwin specific. If no one is complaining about this with non-stdlib distutils on Fedora then likely it is no longer an issue.

So I think this can be closed.

**Comment by lazka** [comment]
Ah, I missed 3.1-enable-new-dtags.patch...

**Comment by lazka** [comment]
I've created #150, as always, feedback welcome.

**Comment by lazka** [comment]
I think this can be closed now

**Comment by DWesl** [comment]
>     2. The only remaining patch is https://cygwin.com/git-cygwin-packages/?p=git/cygwin-packages/python38.git;a=blob;f=00001-rpath.patch;h=aad36128683812464d49ae7f8ff3124e6a71e99e;hb=HEAD which comes from Fedora https://src.fedoraproject.org/rpms/python3.10/blob/4dc2200b8e81beeff7e672aa095f533e87b184c5/f/00001-rpath.patch so it isn't cygwin specific. If no one is complaining about this with non-stdlib distutils on Fedora then likely it is no longer an issue.

I suspect pypa/setuptools#3257 is about this patch no longer being applied on an rpm-based platform.

**Comment by DWesl** [comment]
I just ran into this on Cygwin; pip decided to compile numpy, and failed with 
```bash
    INFO: gcc -shared -Wl,--enable-auto-image-base [whole bunch of input files]  -L/usr/lib -Lbuild/temp.cygwin-3.3.5-x86_64-3.8 -Wl,--enable-new-dtags,-R/usr/lib -lnpymath -lblas -lblas -lpython3.8 -o build/lib.cygwin-3.3.5-x86_64-3.8/numpy/core/_multiarray_umath.cpython-38-x86_64-cygwin.dll
    /usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: unrecognized option '--enable-new-dtags'
    /usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: use the --help option for usage information
    collect2: error: ld returned 1 exit status
```
There's a chance this is because I set `BLAS=/usr/lib/libblas.dll.a`, and this would happen even with [that second patch](https://cygwin.com/git-cygwin-packages/?p=git/cygwin-packages/python38.git;a=blob;f=00001-rpath.patch;h=aad36128683812464d49ae7f8ff3124e6a71e99e;hb=HEAD) if I set `BLAS=/home/me/lib/myblas.dll.a`, but applying that patch would allow the most common cases to work.
