### ISSUE TITLE
Support MSYS2 (mingw)

### ISSUE THREAD

**Issue by jaraco** [pypa/distutils#74]
Same for MSYS2 (mingw). Patches are here: https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-python

_Originally posted by @mkoeppe in https://github.com/pypa/distutils/issues/73#issuecomment-991733375_

**Comment by jaraco** [comment]
For testing on MSYS2, there is a GH Action: https://github.com/msys2/setup-msys2

**Comment by naveen521kk** [comment]
I remember making an issue a while ago: https://github.com/pypa/distutils/issues/34 😄 
Just FYI we moved the patch to Git: https://github.com/msys2-contrib/cpython-mingw/commits/mingw-v3.9.7/Lib/distutils

I and @lazka could help out adding those patches here along with a CI to test them.
Thanks.

**Comment by jaraco** [comment]
Oh, excellent. So this is a duplicate. Thanks!
