### ISSUE TITLE
Support Homebrew patches

### ISSUE THREAD

**Issue by jaraco** [pypa/distutils#76]
From Homebrew's side we completely override the prefix (`base` var). This is because under our system, the Python install directory and the install directory that should be used for user-installed packages should be separate (or user packages are lost on upgrades).

We currently do this via `distutils.cfg` planted in the standard library distutils which will of course not work anymore.

Going forward we're looking at the system that will hopefully be introduced in Python 3.11 to add additional install schemes to sysconfig.py:

- https://gist.github.com/FFY00/625f65681fbcd7fc039dd4d727bb2c2f
- https://bugs.python.org/issue43976

Notably, the idea is schemes should be _added_ rather than replaced. This is why `sysconfig.get_preferred_scheme(key)` was introduced in Python 3.10. This is also important when dynamic logic may be required. Ideally I reckon distutils should use this when selecting a scheme.

While the above will cover Python 3.10+, there'll still be a question about what we do for <= 3.9. `sysconfig._prefix_addition` is almost what we want, though I don't know if calculating a relative path and going up levels (`..`) is a good idea.

_Originally posted by @Bo98 in https://github.com/pypa/setuptools/issues/2896#issuecomment-992774977_

**Comment by jaraco** [comment]
The preferred and expected long-term supported way for any Python environment to customize the install behavior is to provide custom install schemes as [solicited here](https://github.com/pypa/distutils/blob/92082ee42c80b4a087053118e493cfa07084d867/distutils/command/install.py#L90-L95), and this technique is supported on all supported Pythons (3.6+). So if homebrew can patch/extend the install schemes in sysconfig, that would be the best solution for old and new Pythons. If it's going to be more complicated than that, capture any shortcomings here and we can discuss.

**Comment by jaraco** [comment]
It seems distutils needs to support that get preferred scheme, which presumably could be honored even on old Pythons. I can work on an implementation this weekend. If Homebrew can patch sysconfig to extend the schemes and provide a get preferred scheme function, would that provide foreword and backward compatibility?

**Comment by Bo98** [comment]
Yes, it seems likely we will backport `get_preferred_scheme` to older Pythons so that plan sounds good to me.
