### ISSUE TITLE
distutils access `['headers']` from sysconfig scheme but the key in sysconfig is `['include']`

### ISSUE THREAD

**Issue by asottile** [pypa/distutils#88]
I suspect this is the cause of this trace, but I have yet to track down a reproduction: https://github.com/deadsnakes/issues/issues/191#issue-1086418684

here's where the key is accessed: https://github.com/pypa/distutils/blob/5ed4fe50f31641937adf1da1a3f578365661b87e/distutils/command/install.py#L154-L155

and here's where that key list is: https://github.com/pypa/distutils/blob/5ed4fe50f31641937adf1da1a3f578365661b87e/distutils/command/install.py#L92

here's an example sysconfig entry:
https://github.com/python/cpython/blob/31ff96712e8f89ac1056c2da880b44650002219f/Lib/sysconfig.py#L27-L38

here's what cpython does for this:
https://github.com/python/cpython/blob/31ff96712e8f89ac1056c2da880b44650002219f/Lib/distutils/command/install.py#L45-L51

**Comment by FFY00** [comment]
No, `headers` and `include` are two different keys with different values. I think the bug that lead to the issue you linked was introduced in #79, which I did not have a chance to review.

cc @jaraco

**Comment by jaraco** [comment]
Probably #79 was implicated but also #23, where we learned that sysconfig supplies `include` and distutils requires `headers` and they're different things. The solution was to provide compatibility by continuing to supply the legacy install schemes with `headers` definitions. This also means that if a custom scheme is provided, it also needs to provide `headers` or needs to opt out of this distutils with SETUPTOOLS_USE_DISTUTILS=stdlib (for now).

If someone has an idea how distutils could rely on `include` instead of `headers`, I'd be interested in a patch to support that transition.

**Comment by jaraco** [comment]
I can see in https://github.com/python/cpython/commit/341e8a939aca6e9f59ffb0e6daee5888933694ed#diff-ad882d2747b67da1f6b5a8d3a08f0865ee7bb9fd88c4e8e3ff946d338606e818R41-R42 where CPython's copy of distutils simply treats 'include' as 'headers' and then [appends the dist name](https://github.com/python/cpython/commit/341e8a939aca6e9f59ffb0e6daee5888933694ed#diff-ad882d2747b67da1f6b5a8d3a08f0865ee7bb9fd88c4e8e3ff946d338606e818R55). Probably this version of distutils could do the same.

**Comment by FFY00** [comment]
That is not correct, I didn't notice it earlier but it's a bug in the CPython implementation.

See https://bugs.python.org/issue44445 for some context.

**Comment by jaraco** [comment]
Thanks Filipe for pointing me to that bug (again). That's really helpful.

As I understand it, the long term fix (in that bug) is to provide another key such as `site-include`.

The medium-term fix is for platforms to include a `headers` key for any custom scheme. Perhaps CPython should include some guidance on the need for this key until `site-include` exists.

A short-term fix might be for distutils to use the `headers` key from the default scheme (ignoring preferred) whenever the preferred scheme does not define `headers`.

**Comment by jaraco** [comment]
Setuptools PR at pypa/setuptools#2960.
