### ISSUE TITLE
50.0.0 can't build extensions for Python < 3.8 if Py_ENABLE_SHARED

### ISSUE THREAD

**Issue by godlygeek** [pypa/distutils#9]
For Python 3.7 and lower, if the interpreter is built as `Py_ENABLE_SHARED`, the interpreter core is built into a libpython shared library, and extension modules built for that interpreter need to link against that shared library when they are built. This [changed in 3.8](https://docs.python.org/3/whatsnew/3.8.html#debug-build-uses-the-same-abi-as-release-build):

> On Unix, C extensions are no longer linked to libpython except on Android and Cygwin.

`setuptools` 50.0.0 does not include libpython in the link command when building for a Python 3.7 `Py_ENABLE_SHARED` interpreter, so extensions that can build successfully with 49.6.0 fail to link with 50.0.0.

Presumably this is because 50.0.0 is using a vendored `distutils` that was copied from a recent CPython, and support for linking against libpython was dropped there because it is no longer used after 3.8, but it is still required for older versions.

**Comment by jaraco** [comment]
Fix releasing with setuptools 50.0.3.
