### ISSUE TITLE
Should the test suite depend on `test.support`?

### ISSUE THREAD

**Issue by lazka** [pypa/distutils#98]
Various things in the test suite depend on the CPython internal `test.support` module: https://github.com/pypa/distutils/search?q=test.support

* Should we move the used functionality here?
* If yes, what is the licensing situation of this module i.e. can I just copy things?

This came up in #95 which fails because some API in `test.support` is different depending on the Python version.

**Comment by jaraco** [comment]
In my experience, `test.support` is available for use, so my preference is to continue to use it here. Once Setuptools fully adopts distutils (or as part of that adoption), the test suite will be ported to pytest-native code and any fixtures from `test.support` can considered for migration to local fixtures.

I too have encountered issues where the fixtures have moved (for Python 3.9 a lot was moved). For those I create [compatibility modules like py38compat](https://github.com/pypa/distutils/blob/main/distutils/tests/py38compat.py) to provide the compatible functionality across Python versions.

I'll explore this possibility in #95.

**Comment by lazka** [comment]
ok, I see, thanks. feel free to close this then.
